### ISSUE TITLE
[BUG] This has issues staying "open"

### ISSUE THREAD

**Issue by Biliskn3r** [eythaann/Seelen-UI#196] opened 2024-10-20 17:17 UTC
**Computer locked. When you come back (1, 2 minutes - 1 hour), the program is terminated. You can tell because the windows 11 taskbar is on the bottom.**

**Comment by ljbred08** [comment] 2024-11-08 16:45
I have the same problem: when I come back after the computer has been locked, I have to manually start Seelen again.

**Comment by ljbred08** [comment] 2024-11-10 22:08
Also, I think this is a duplicate of #102.

**Closed** 2024-11-10 22:38 UTC
Labels: bug, duplicate
