### ISSUE TITLE
[BUG] Crashes after running for a few seconds

### ISSUE THREAD

**Issue by Gwen0x4c3** [eythaann/Seelen-UI#87] opened 2024-09-04 17:20 UTC
**Environment**
OS: Windows 10
Language: 简体中文

**Logs**
[2024-09-04][17:12:42][seelen_ui][INFO] ───────────────────── Starting Seelen UI v1.10.4 ─────────────────────
[2024-09-04][17:12:42][seelen_ui][INFO] Operating System: Windows 10.0.19045 (Windows 10 Pro) [64-bit]
[2024-09-04][17:12:42][seelen_ui][INFO] Locate: Some("zh-CN")
[2024-09-04][17:12:42][seelen_ui][INFO] Elevated: Ok(true)
[2024-09-04][17:12:42][seelen_ui::modules::cli][INFO] TCP server listening on 127.0.0.1:16571
[2024-09-04][17:12:42][seelen_ui::seelen][TRACE] Ensuring folders
[2024-09-04][17:12:42][seelen_ui::seelen][TRACE] Initializing Seelen
[2024-09-04][17:12:42][seelen_ui::state::application][TRACE] Creating new State Manager
[2024-09-04][17:12:42][seelen_ui::state::application][TRACE] Starting Seelen UI Files Watcher
[2024-09-04][17:12:42][seelen_ui::seelen][TRACE] Show settings window
[2024-09-04][17:12:43][seelen_ui::seelen][TRACE] Showing update notification window
[2024-09-04][17:12:43][seelen_ui::seelen][TRACE] Enumerating Monitors
[2024-09-04][17:12:43][seelen_ui::seelen_bar][INFO] Creating fancy-toolbar/DISPLAY1
[2024-09-04][17:12:43][seelen_ui::seelen_weg][INFO] Creating seelenweg/DISPLAY1
[2024-09-04][17:12:44][reqwest::connect][DEBUG] starting new connection: https://github.com/
[2024-09-04][17:12:44][reqwest::connect][DEBUG] proxy(http://127.0.0.1:10809) intercepts 'https://github.com/'
[2024-09-04][17:12:44][reqwest::connect][TRACE] tunneling HTTPS over proxy
[2024-09-04][17:12:44][seelen_ui::tray][TRACE] registering tray icon
[2024-09-04][17:12:44][seelen_ui::seelen][TRACE] Killing AHK shortcuts
[2024-09-04][17:12:45][seelen_ui::seelen][TRACE] Creating AHK shortcuts
[2024-09-04][17:12:45][seelen_ui::seelen][TRACE] AHK shortcuts started successfully
[2024-09-04][17:12:45][seelen_ui::modules::system_settings::infrastructure][TRACE] Registering colors events
[2024-09-04][17:12:45][reqwest::async_impl::client][DEBUG] redirecting 'https://github.com/eythaann/Seelen-UI/releases/latest/download/latest.json' to 'https://github.com/eythaann/Seelen-UI/releases/download/v1.10.4/latest.json'
[2024-09-04][17:12:46][reqwest::async_impl::client][DEBUG] redirecting 'https://github.com/eythaann/Seelen-UI/releases/download/v1.10.4/latest.json' to 'https://objects.githubusercontent.com/github-production-release-asset-2e65be/758623687/a1acb74c-2298-428f-9dd1-94687f1470a3?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=releaseassetproduction%2F20240904%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20240904T171245Z&X-Amz-Expires=300&X-Amz-Signature=8b2fe63637b72b59d37233282d5915883a4399efb2de0d4da5ebb8f75c47ca9f&X-Amz-SignedHeaders=host&actor_id=0&key_id=0&repo_id=758623687&response-content-disposition=attachment%3B%20filename%3Dlatest.json&response-content-type=application%2Foctet-stream'
[2024-09-04][17:12:46][reqwest::connect][DEBUG] starting new connection: https://objects.githubusercontent.com/
[2024-09-04][17:12:46][reqwest::connect][DEBUG] proxy(http://127.0.0.1:10809) intercepts 'https://objects.githubusercontent.com/'
[2024-09-04][17:12:46][reqwest::connect][TRACE] tunneling HTTPS over proxy
[2024-09-04][17:12:46][seelen_ui::modules::tray::infrastructure][TRACE] Registering tray events
[2024-09-04][17:12:46][seelen_ui::modules::network::infrastructure][TRACE] Registering network events
[2024-09-04][17:12:46][seelen_ui::modules::power::infrastructure][TRACE] Registering system power events
[2024-09-04][17:12:46][seelen_ui::modules::notifications::application][DEBUG] Failed to use NotificationChanged: Error { code: HRESULT(0x80070490), message: "找不到元素。" }, spawning thread instead
[2024-09-04][17:12:46][seelen_ui::modules::media::infrastructure][TRACE] Registering media events
[2024-09-04][17:12:46][seelen_ui::modules::notifications::infrastructure][TRACE] Registering notifications events
[2024-09-04][17:12:46][seelen_ui::seelen_weg::icon_extractor][TRACE] Extracting icon for "explorer.exe"
[2024-09-04][17:12:46][seelen_ui::modules::uwp][TRACE] Loading UWP packages
[2024-09-04][17:12:47][seelen_ui][ERROR] A panic occurred:
  Cause: [36mFailed to refresh UWP manager: SerdeJson(Error("EOF while parsing a value", line: 1, column: 0))[39m
  Location: [35msrc/background\modules\uwp\mod.rs:24:27[39m
[2024-09-04][17:12:47][seelen_ui][ERROR] A panic occurred:
  Cause: [36mpanic in a function that cannot unwind[39m
  Location: [35mlibrary\core\src\panicking.rs:221:5[39m

**Comment by victornavorskie** [comment] 2024-09-10 10:58
same here

**Comment by Gwen0x4c3** [comment] 2024-09-10 13:20
I solved this problem by updating to win11😂

**Comment by eythaann** [comment] 2024-09-10 13:25
> I solved this problem by updating to win11😂

this issue is caused by some uwp app with a unsupported character on utf8 I'm migrating all the code to use utf16 instead this is a thing that I don't take in care when starting developing the app.

**Comment by eythaann** [comment] 2024-09-10 13:26
so yeah you're issue will look solved on a fresh install of windows because you remove the app with the unsupported character

**Comment by Gwen0x4c3** [comment] 2024-09-10 13:35
> so yeah youre issue will look solved on a fresh install of windows because you remove the app with the unsupported character

now i get it😀

**Comment by PhantomPixel-0418** [comment] 2024-10-05 03:56
https://github.com/user-attachments/assets/85d711d8-a07f-4eed-ae75-f89c59c0b6d4

**Comment by eythaann** [comment] 2024-10-05 06:39
this will be fixed on the next beta 15 version cuz I refactor the way to handle uwp icons, so this ticket will be market as closed.

**Closed by eythaann** 2024-10-05 06:39 UTC
Labels: bug, priority-1
