### ISSUE TITLE
[BUG] Windows arm architecture compatibility.

### ISSUE THREAD

**Issue by rexxDZN** [eythaann/Seelen-UI#165] opened 2024-10-16 22:20 UTC
**Describe the bug**
Please create a windows arm version. This will help the app run (smoothly) and use less battery life.

**Comment by eythaann** [comment] 2024-10-17 04:22
there is a arm version but is still on testing stage.

**Comment by eythaann** [comment] 2024-11-24 07:38
This will be performed but is not a bug, so I will close this issue.

**Closed by eythaann** 2024-11-24 07:38 UTC
Labels: bug

**Comment by rexxDZN** [comment] 2024-12-25 18:41
> there is a arm version but is still on testing stage.

Do u have any update on this? i'd love to try it out

**Comment by eythaann** [comment] 2024-12-26 01:24
not yet.
