### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by elkhaligy** [eythaann/Seelen-UI#67] opened 2024-08-30 13:15 UTC
Hi, the program is crashing after like 3 seconds, here's the log file
[Seelen UI.log](https://github.com/user-attachments/files/16817531/Seelen.UI.log)

**Comment by eythaann** [comment] 2024-08-30 13:33
it looks like some value is null on reading UWP info, let me try a fix abut I'm no able to replicate this so you will have to test it.

**Comment by elkhaligy** [comment] 2024-08-30 14:43
> it looks like some value is null on reading UWP info, let me try a fix abut I'm no able to replicate this so you will have to test it.

Ok

**Comment by elkhaligy** [comment] 2024-08-30 16:33
Do you think it is because I uninstalled Edge? but I left webview

**Comment by eythaann** [comment] 2024-08-30 17:16
you need edge, but the crash is caused by other issue.

**Comment by eythaann** [comment] 2024-08-30 22:45
@elkhaligy tag me if the problem persist, but this in theory should be fixed on v1.10.1

**Closed by eythaann** 2024-08-30 22:45 UTC
Labels: bug, priority-1
