### ISSUE TITLE
App cannot start

### ISSUE THREAD

**Issue by zengyjie** [eythaann/Seelen-UI#291] opened 2024-11-27 15:54 UTC
**Describe the bug**
The app was working fine, i uninstalled and reinstalled it and it stops working, now the microsoft store version runs for about 2s before closing (nothing happens) and the web downloaded version does not run unless run as administrator, and then behaves like the microsoft version
i have fully uninstalled with revo etc

**Comment by eythaann** [comment] 2024-11-27 15:56
The issue is on fresh installations, it was fixed on v2.0.7

**Closed by eythaann** 2024-11-27 15:56 UTC
Labels: bug
