### ISSUE TITLE
[BUG] Network status shows ethernet icon when connected to wi-fi

### ISSUE THREAD

**Issue by Joshua-Nweze** [eythaann/Seelen-UI#294] opened 2024-11-30 06:09 UTC
When I connect to a wi-fi, the network status icon wont show a wi-fi icon but an ethernet icon

![Screenshot 2024-11-30 041402](https://github.com/user-attachments/assets/405de82b-6ee9-48e9-8a17-5376ac5ec811)

**Comment by PhantomPixel-0418** [comment] 2024-11-30 07:39
Yeah, I'm having this problem too
I'm connected to Ethernet and it's incorrectly showing the WiFi icon
![image](https://github.com/user-attachments/assets/a2938475-aeb0-4e53-b3c5-f58d60f5cbc5)
Although the settings in the picture are not in English, we can see that there is an Ethernet logo and that my WiFi function is turned off, which reflects a possible confusion between the two icons

**Comment by luriusTM** [comment] 2024-11-30 12:45
There is a problem about that... the used connection view is not updated because currently there is NLM_Connectivity subscribtion for that... which is is in definition is not for network adapter change, but for internet accessibility change. So when you change network adapter for wlan to lan but wlan had internet also, NLM_CONNECTIVITY connectivity remains 66 (internet access) and vica versa. Also there is still an active wlan whn you loose lan connection windows switch to that immediately. 

Had already done the root cause analysis before, but did not resolved that time, cause different issue was bigger. Will look on that, what I can do for this cause nowadays.

**Comment by luriusTM** [comment] 2024-11-30 19:53
Solved both of your problems :) 

When the above will be merged, the lan connection will be visible on component as separated instance. 

Found the "issue" on BE and generated an event occurrence in case of IP change.

**Comment by luriusTM** [comment] 2024-12-01 08:55
> Solved both of your problems :)
> 
> When the above will be merged, the lan connection will be visible on component as separated instance.
> 
> Found the "issue" on BE and generated an event occurrence in case of IP change. Behaviour when disconnect and then connect lan cable
> 
>  Screen.Recording.2024-11-30.204623.mp4

As for UI, this was not a good choice from my side, so got to remove that, but the main issue resolved and the TB icon modifies as desired.

https://github.com/user-attachments/assets/200353e9-52d8-459f-97b8-8e99b8a1e14e

**Closed** 2024-12-04 01:05 UTC
Labels: bug, toolbar
