### ISSUE TITLE
[BUG] Chrome Apps

### ISSUE THREAD

**Issue by HgGamer** [eythaann/Seelen-UI#78] opened 2024-09-02 06:49 UTC
Chrome apps, that are running on separate windows, like Rocket Chat, on default windows look like a separate app. But with Seelen-UI they are sorted under the chrome icon on the taskbar.

**Comment by eythaann** [comment] 2024-09-02 07:14
duplicate of #77

**Closed by eythaann** 2024-09-02 07:14 UTC
Labels: bug, duplicate
