### ISSUE TITLE
[BUG] Dock bar bug

### ISSUE THREAD

**Issue by klaybloom** [eythaann/Seelen-UI#287] opened 2024-11-22 00:47 UTC
**Describe the bug**
Right-click dock bar when the application icon selection fixed, the right-click menu has been flashing and can not be selected.
**To Reproduce**
1. Go to 'dick bar'
2. Click on 'fixed'
3. See error

**Expected behavior**
can fixed the application in dock bar and right-click menu can be selected.

**Screenshots**
![88bbe2c98e36be48e5edc62afbeac50](https://github.com/user-attachments/assets/6e74b19f-5e46-4a7f-be4a-3ca85f6ab90f)

**Comment by PhantomPixel-0418** [comment] 2024-11-23 00:13
@klaybloom

是的，这样确实会引发这样的错误。

- 因为在当你的鼠标放在提示框上时，dock栏会变成原来的大小，
- 所以有几率缩小后你的鼠标会回到图标上；

- 又因为有可能您的鼠标会回到图标上，
- 所以dock栏会重新放大。

---

Yes, this does trigger such an error.

- Because the dock bar becomes the original size when you mouse over the hint box, 
- so there's a chance that after shrinking it your mouse will go back to the icon; 
- 
- and because there's a chance that your mouse will go back to the icon, 
- so the dock bar will be enlarged again.

**Comment by luriusTM** [comment] 2024-11-23 14:54
I'm typically love hunting for these kind of behaviour... I've already fixed some in an ppen PR, I'm trying to reproduce what you write, but I do not get what you planned to mean... It is almost sure something which is translated cause you do understand each other... could you please video what you do, or could give a step-by-step guide (with images) to me to understand what you did... 

I've done some rounds on my last branch of fixies do I found any unintentional, but I did not succeed. :) If any of you can send me a video about the exact happenings, I try to help :)

**Comment by eythaann** [comment] 2024-11-24 07:24
Already fixed on v2.0.6-rc.0

**Closed by eythaann** 2024-11-24 07:24 UTC
Labels: bug
